-- Donnees facultatives : importer une seule fois apres questionaire.sql.
-- Chaque import ajoute trois quiz. Aucun contenu existant n'est efface.
USE questionaire;
SET NAMES utf8mb4;
START TRANSACTION;
INSERT INTO utilisateurs (Username) VALUES ('La sélection Quizzhub');
SET @demo_author = LAST_INSERT_ID();
INSERT INTO questionaires (Name, Type, ID_Utilisateur, Note_Moyenne) VALUES ('Spécial années 2000', 'Culture générale', @demo_author, 0);
SET @demo_quiz = LAST_INSERT_ID();
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel réseau social Mark Zuckerberg a-t-il lancé en 2004 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Facebook', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Twitter', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Instagram', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Snapchat', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle console de Nintendo, sortie en 2006, se joue avec une télécommande à détection de mouvement ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La Wii', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La GameCube', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La Xbox 360', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La PlayStation 3', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel film de James Cameron sorti en 2009 a battu le record du box-office mondial ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Avatar', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Titanic', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Roi Lion', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Jurassic Park', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle chanteuse a sorti l''album « Back to Black » en 2006 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Amy Winehouse', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Adele', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Rihanna', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Duffy', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('En quelle année les pièces et billets en euros sont-ils entrés en circulation ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2002', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1999', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2000', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2004', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel baladeur lancé par Apple en 2001 a changé l''écoute de la musique ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('L''iPod', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Walkman', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Zune', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Discman', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel pays a organisé la Coupe du monde de football en 2006 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('L''Allemagne', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La France', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('L''Afrique du Sud', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Japon', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle série lancée en 2004 suit des rescapés d''un crash sur une île mystérieuse ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Lost', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Prison Break', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Heroes', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Dexter', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('En quelle année Google est-il entré en bourse ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2004', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1998', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2001', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('2008', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel film d''animation Pixar de 2003 raconte la recherche d''un poisson-clown ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Monde de Nemo', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Wall-E', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Ratatouille', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Là-haut', @demo_question, 'Faux');
INSERT INTO questionaires (Name, Type, ID_Utilisateur, Note_Moyenne) VALUES ('Cinéma : les incontournables', 'Cinéma', @demo_author, 0);
SET @demo_quiz = LAST_INSERT_ID();
INSERT INTO questions (Question, ID_Questio) VALUES ('Qui a réalisé « Titanic », sorti en 1997 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('James Cameron', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Steven Spielberg', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Ridley Scott', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Martin Scorsese', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Dans quelle saga trouve-t-on la planète Tatooine ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Star Wars', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Dune', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Star Trek', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Le Cinquième Élément', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel acteur incarne Jack Sparrow dans « Pirates des Caraïbes » ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Johnny Depp', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Orlando Bloom', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Javier Bardem', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Brad Pitt', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Dans quel royaume imaginaire se déroule « Game of Thrones » ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Westeros', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Narnia', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La Terre du Milieu', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Panem', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel studio a produit « Toy Story », premier long-métrage entièrement en images de synthèse ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Pixar', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('DreamWorks', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Illumination', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Blue Sky', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel film de Bong Joon-ho a remporté l''Oscar du meilleur film en 2020 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Parasite', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Roma', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1917', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Joker', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Dans « Retour vers le futur », quel véhicule sert de machine à voyager dans le temps ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une DeLorean', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une Coccinelle', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Un bus scolaire', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une Chevrolet', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle actrice incarne Hermione Granger dans les films Harry Potter ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Emma Watson', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Emma Stone', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Bonnie Wright', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Evanna Lynch', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel réalisateur japonais a signé « Le Voyage de Chihiro » ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Hayao Miyazaki', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Isao Takahata', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Makoto Shinkai', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Mamoru Hosoda', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel film a lancé l''univers cinématographique Marvel en 2008 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Iron Man', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Avengers', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Thor', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Captain America', @demo_question, 'Faux');
INSERT INTO questionaires (Name, Type, ID_Utilisateur, Note_Moyenne) VALUES ('Voyage dans le système solaire', 'Sciences', @demo_author, 0);
SET @demo_quiz = LAST_INSERT_ID();
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle est la planète la plus proche du Soleil ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Mercure', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Vénus', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Mars', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('La Terre', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle est la plus grande planète du système solaire ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Jupiter', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Saturne', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Neptune', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Uranus', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Combien de temps met la lumière du Soleil pour nous parvenir ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Environ 8 minutes', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Environ 8 secondes', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Environ 1 heure', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Environ 1 jour', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Sur quelle planète se trouve Olympus Mons, le plus grand volcan connu ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Mars', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Vénus', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Jupiter', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Mercure', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle sonde lancée en 1977 a quitté l''héliosphère en 2012 ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Voyager 1', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Pioneer 10', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Cassini', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('New Horizons', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quel satellite de Saturne possède une atmosphère dense et des lacs de méthane ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Titan', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Europe', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Ganymède', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Phobos', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Quelle planète tourne pratiquement couchée sur son orbite ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Uranus', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Neptune', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Vénus', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Saturne', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('Une année-lumière mesure quoi, exactement ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une distance', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une durée', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une vitesse', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('Une masse', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('En quelle année ont eu lieu les premiers pas sur la Lune ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1969', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1961', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1972', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('1957', @demo_question, 'Faux');
INSERT INTO questions (Question, ID_Questio) VALUES ('De quoi les anneaux de Saturne sont-ils principalement composés ?', @demo_quiz);
SET @demo_question = LAST_INSERT_ID();
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('De blocs de glace', @demo_question, 'Vrai');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('De gaz', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('De poussière métallique', @demo_question, 'Faux');
INSERT INTO reponse (Rep, ID_Questions, Is_Correct) VALUES ('De lave refroidie', @demo_question, 'Faux');
COMMIT;
